sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t arushsoel/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true arushsoel/docker-react npm run test

